on: [ push, pull_request ]
name: test
jobs:
  test:
    strategy:
      matrix:
        elasticsearch-version: [ 8.2.3, 8.2.0 , 8.1.3, 7.17.3, 7.16.3, 7.15.2, 7.14.2]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Get License
        run: |
          wget "https://github.com/NLPIR-team/NLPIR/raw/master/License/license%20for%20a%20month/NLPIR-ICTCLAS%E5%88%86%E8%AF%8D%E7%B3%BB%E7%BB%9F%E6%8E%88%E6%9D%83/NLPIR.user" -O NLPIR.user
          cp NLPIR.user src/main/packaging/Data/
      - name: Test
        run: |
          ./gradlew test \
            -i \
            -PelasticsearchVersion=${{matrix.elasticsearch-version}} \
            -Dfile.encoding=UTF8
      - name: Yaml Rest Test
        run: |
          ./gradlew yamlRestTest \
            -i \
            -PelasticsearchVersion=${{matrix.elasticsearch-version}} \
            -Dfile.encoding=UTF8